@echo off
echo Starting Dora daemon...
start /B dora up

echo Waiting for daemon to start...
timeout /t 5 /nobreak >nul

echo Building dataflow...
dora build dataflow.yml

echo Starting dataflow...
dora start dataflow.yml
