@echo off
echo Starting Dora daemon...
start /B dora up

echo Waiting for daemon to start...
timeout /t 5 /nobreak >nul

echo Building multi-view capture dataflow...
dora build dataflow_capture.yml

echo Starting multi-view capture...
dora start dataflow_capture.yml
